//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public int asset_id { get; set; }
        public string asset_ip { get; set; }
        public string asset_host { get; set; }
        public string asset_Os { get; set; }
        public System.DateTime asset_dt { get; set; }
        public string asset_uname { get; set; }
    }
}
