//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileLog
    {
        public int f_id { get; set; }
        public string f_name { get; set; }
        public string f_path { get; set; }
        public string f_action { get; set; }
        public System.DateTime f_dtime { get; set; }
        public string f_hname { get; set; }
    }
}
